{
 "title": "dermatology-disease-random-forest",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Not Stable Predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_not_stable_prediction FROM dermatology_disease LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM dermatology_disease LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM dermatology_disease LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM dermatology_disease LIMIT 50 "
    }
   ]
  }
 ]
}